### ISSUE TITLE
Placeholder is missing for upload fields

### ISSUE THREAD

**Issue by tristanlins** [contao-bootstrap/form#11]
The placeholder seems working for upload fields, but the settings field in the form generator is missing.

**Comment by dmolineus** [comment]
> The placeholder seems working for upload fields

How it is working? When I have a text field with placeholder and switch the type to an upload field, the placeholder is not used.

**Comment by tristanlins** [comment]
You're right, I did a little modification to the netzmacht/contao-form-helper package: https://github.com/netzmacht/contao-form-helper/compare/master...tristanlins:patch-1

![placeholder](https://cloud.githubusercontent.com/assets/343404/6717536/85177cbc-cdad-11e4-9604-783620de210e.png)

**Comment by dmolineus** [comment]
Ok, I probably add it only for bootstrap because with the default upload field the placeholder attribute doesn't make any sense (as far as I know no browsers support it there).

**Comment by tristanlins** [comment]
Yes, thats right, but with bootstrap it works very nice :-)
