### ISSUE TITLE
Fatal Error nur bei form

### ISSUE THREAD

**Issue by csaeum** [contao-bootstrap/form#12]
Hallo ich bekomme seit neuesten bei der neuinstallation von contao-bootstrap/bundle folgende Meldung:
Fatal error: Uncaught exception Exception with message Cannot create symlink module, file exists and is not a link thrown in composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/SymlinkInstaller.php on line 120

#0 composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/SymlinkInstaller.php(41): ContaoCommunityAlliance\Composer\Plugin\SymlinkInstaller->updateAllSymlinks(Array, '/kunden/451430_...', '/kunden/451430_...', 0)
#1 composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/AbstractInstaller.php(138): ContaoCommunityAlliance\Composer\Plugin\SymlinkInstaller->updateSources(Array, Object(Composer\Package\CompletePackage))
#2 phar://composer/composer.phar/src/Composer/Installer/LibraryInstaller.php(87): ContaoCommunityAlliance\Composer\Plugin\AbstractInstaller->installCode(Object(Composer\Package\CompletePackage))
#3 phar://composer/composer.phar/src/Composer/Installer/InstallationManager.php(152): Composer\Installer\LibraryInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 phar://composer/composer.phar/src/Composer/Installer/InstallationManager.php(139): Composer\Installer\InstallationManager->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#5 phar://composer/composer.phar/src/Composer/Installer.php(597): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#6 phar://composer/composer.phar/src/Composer/Installer.php(232): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array, false)
#7 composer/vendor/contao-community-alliance/composer-client/src/system/modules/!composer/src/Controller/UpdatePackagesController.php(151): Composer\Installer->run()
#8 composer/vendor/contao-community-alliance/composer-client/src/system/modules/!composer/src/Controller/UpdatePackagesController.php(55): ContaoCommunityAlliance\Contao\Composer\Controller\UpdatePackagesController->runInline(Array, false)
#9 composer/vendor/contao-community-alliance/composer-client/src/system/modules/!composer/src/ClientBackend.php(218): ContaoCommunityAlliance\Contao\Composer\Controller\UpdatePackagesController->handle(Object(Contao\Input))
#10 system/modules/core/classes/Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#11 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('composer')
#12 contao/main.php(20): Contao\BackendMain->run()
#13 {main}

drücke ich reload kommt diese Meldung immer wieder:

Gehe ich danach wieder auf composer im Backend erscheint diese Meldung und pro reload dann jeweile eine Meldung mehr (hier war es ein reload)

Loading composer repositories with package information
Updating dependencies
  - Installing contao-bootstrap/form (1.0.3)
    Loading from cache

Loading composer repositories with package information
Updating dependencies
  - Installing contao-bootstrap/form (1.0.3)
    Loading from cache

Vielleicht könnt ihr was damit anfangen?

**Comment by dmolineus** [comment]
Danke erst einmal für den Report mit ausführlicher Fehlermeldung. Das hilft schon mal weiter. :) Bitte in Zukunft die Fehlermeldung entsprechend [kodieren](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks), sonst verlinkt Github die Zeilennummer fälschlicherweise mit Tickets.

Der Fehler hat nichts mit contao-bootstrap zu tun, sondern wird durch Composer hervorgerufen. Er kann das Modul nicht unter `system/modules/` installieren, da dies hier als Ordner vorliegt. Dieser kann nicht mit einem Symlink überschrieben werden.

Dieser Fehler tritt z.B. dann auf, wenn man die Installationsart von Composer von Distributionsarchiv auf Quellen im nachhinein ändert. um den Fehler zu beheben, am besten alle Module (außer die Standard Contao Module und !composer) unter `system/modules/` löschen, nochmals Pakete aktualisieren. Ggf. noch einmal Paketverwaltung -> Werkzeuge -> erneute Synchronisierung durchführen.
