### ISSUE TITLE
Button element is not W3C-valid

### ISSUE THREAD

**Issue by sebj54** [contao-bootstrap/form#13]
Hi,

Thanks for your module that is really helpful.
I am just here to tell you that the templates used for the button element is not valid, according to W3C:

![image](https://cloud.githubusercontent.com/assets/5880435/9935301/17ec107e-5d56-11e5-8ee4-96573dff8ace.png)

It shouldn't have an empty `name` value (please make it editable or don't add a `name` attribute to the `button` tag if name is empty) and shouldn't have an `alt` attribute.

Thanks in advance for a fix!

**Comment by dmolineus** [comment]
Name gonna be required. Alt tag is removed. Is part of the 1.1.0-rc1 release.

**Comment by sebj54** [comment]
Thanks for this fix :+1: :)
