### ISSUE TITLE
Fatal error after update: Class 'Netzmacht\Bootstrap\Form\Subscriber' not found in ... EventDispatcherInitializer.php

### ISSUE THREAD

**Issue by CodeAlDente** [contao-bootstrap/form#14]
After updating the packages, I'm getting the following error:

> **PHP Fatal error:** Class 'Netzmacht\Bootstrap\Form\Subscriber' not found in ~/composer/vendor/contao-community-alliance/event-dispatcher/src/ContaoCommunityAlliance/Contao/EventDispatcher/EventDispatcherInitializer.php on line 183

**These are the currently installed packages with their dependencies:**
![1446949027](https://cloud.githubusercontent.com/assets/10899559/11018382/53bd8558-85c7-11e5-8080-d69c771aa904.png)

My work around to get rid off the error message was, to uncomment the line `$GLOBALS['TL_EVENT_SUBSCRIBERS'][] = 'Netzmacht\Bootstrap\Form\Subscriber';` in ~/system/modules/bootstrap-form/config/config.php

**Comment by dmolineus** [comment]
Seems like your project didn't get updated completely. This configuration line got removed in the same commit where the class was removed.

https://github.com/contao-bootstrap/form/commit/59f5b49e7a43a0d41621a6c870365836b7f08bbc
