### ISSUE TITLE
Unknown bootstrap config type "form" (ID 6) stored in database

### ISSUE THREAD

**Issue by niebuhrhood** [contao-bootstrap/form#17]
Hi,
I have a Contao form with Id 6 in DB, and I get the following in logs:

"Unknown bootstrap config type "form" (ID 6) stored in database"

What can a Unknown bootstrap config type "form" be?
Any hint would be appreciated!

**Comment by dmolineus** [comment]
Did you have install the form component and now uninstalled it?

The extension uses a config system which each component can extend and provide it's own config types. Seems like you created a custom form config and removed the bootstrap form component afterwards. If this is not the case I guess there could be an issue with your installation.

**Comment by niebuhrhood** [comment]
Oha, yes this might be.

**Comment by dmolineus** [comment]
You should simply delete the created form config in the bootstrap config module and everything is okay.

**Comment by niebuhrhood** [comment]
Ok, but we use it already. We have to rebuild it.
Thanks for advice!!

**Comment by dmolineus** [comment]
Handling got improvoved with https://github.com/contao-bootstrap/core/commit/a6d0f1642b734f6461dad3d74653c46b5aa35078 so that editing a non existing config is still possible without breaking the backend.

**Comment by niebuhrhood** [comment]
I found an old insert in tl_bootstrap_config and deleted it. 
No more error messages!
