### ISSUE TITLE
Invalid attribute name given bei Platzhalter mit Leerzeichen

### ISSUE THREAD

**Issue by swinde** [contao-bootstrap/form#28]
Beim Anlagen eines Textfeldes bekommt man eine Fehlermeldung "Invalid attribute name given", wenn im Platzhalter ein Leerzeichen steht.

"Ihr_Name" geht --> "Ihr Name" --> "Invalid attribute name given"
Siehe Forum: https://community.contao.org/de/showthread.php?68440-Formular-erstellen-Contao-4-schl%C3%A4gt-fehl&p=453986#post453986

**Comment by dmolineus** [comment]
Thanks for reporting. Fixed in netzmacht/contao-form-designer release 1.0.2.
