### ISSUE TITLE
Palette "email" not found in table "tl_form_field"

### ISSUE THREAD

**Issue by Ma3xl3** [contao-bootstrap/form#31]
Wenn im Formulargenerator bei einem Formular auf "Formular bearbeiten" klicke, bekomme ich folgenden Fehler:

> Internal Server Error
Was ist das Problem?
Palette "email" not found in table "tl_form_field"

Wenn ich im contao_bootstrap.yml folgendes entferne:

> email:
      input_group: true
url:
      input_group: true
number:
      input_group: true
tel:
      input_group: true

und den Cache neu generiere, dann kann ich die Formularelemente bearbeiten.

Mein System:
PHP 7.1.9
Contao 4.4.12
contao-bootstrap/form 2.0.2

**Comment by dmolineus** [comment]
As a workaround installing metapalettes v1.11 should prevent this error.

**Comment by dmolineus** [comment]
As a workaround installing metapalettes v1.11 should prevent this error.

**Comment by dmolineus** [comment]
As a workaround installing metapalettes v1.11 should prevent this error.

**Comment by zonky2** [comment]
hier nochmal den Stack

![error](https://user-images.githubusercontent.com/1045318/35182446-90e0cdf4-fdd5-11e7-9e49-66e743a8d6ed.jpg)

**Comment by dmolineus** [comment]
Should be fixed with f8bda2b which is part of the current hotfix branch (https://github.com/contao-bootstrap/form/tree/hotfix/2.0.3). @zonky2 or @Ma3xl3 could you test it in your environment please if the issue still occurs?

**Comment by Ma3xl3** [comment]
@dmolineus works for me with your hotfix :+1:

**Comment by dmolineus** [comment]
Thanks for the feedback. 2.0.3 includes this fix.
