### ISSUE TITLE
Pflichtfeld - required-Tag fehlt

### ISSUE THREAD

**Issue by mj1985** [contao-bootstrap/form#32]
Moin,
unter Verwendung von Contao 4.4.13 und dem contao-bootstrap/bundle 2.0.0 musste ich feststellen das die Pflichtfelder (Textfeld, Select Menü) kein required-Tag erhalten.
Im Feld "Checkbox-Menü" hingegen schon.
Formular-Layout ist Bootstrap Standard ausgewählt, keine weiteren Einstellungen vorgenommen.

Beispiele: 
Select-Menü

```
<div class="widget widget-select select mandatory form-group">
<label class="select mandatory" for="ctrl_36"><span class="sr-only">Pflichtfeld </span>Anrede<span class="mandatory">*</span>
</label>
<select class="select mandatory form-control custom-select" id="ctrl_36" name="anrede">
<option value="frau">Frau</option>
<option value="Herr">Herr</option>
</select>
</div>
```

Und das Textfeld:
```
<div class="widget widget-text mandatory form-group">
<label class="mandatory" for="ctrl_37">
<span class="sr-only">Pflichtfeld </span>Nachname<span class="mandatory">*</span>
</label>
<input class="mandatory form-control" id="ctrl_37" name="nachname" type="text" value="">
</div>
```

Ohne das required-Tag ist die HTML5-Validierung nutzlos, da sie nur bei Checkbox funktioniert.

**Comment by dmolineus** [comment]
Hab mir den Fehler angesehen. Verursacht durch netzmacht/contao-form-designer. Bei mir funktioniert es nun. Das Checkbox-Menü hat ja an sich kein Required-Attribut, da sonst ja jede Checkbox davon betroffen wäre.

Wäre super, wenn du mir bestätigen könntest, dass es bei dir auch überall funktioniert, wie erwartet. Dazu bitte folgendes installieren:

```bash
composer require netzmacht/contao-form-designer:dev-hotfix/1.0.6 as 1.0.6
```

**Comment by mj1985** [comment]
Funktioniert bei mir auf allen Formularten nun wunderbar!

**Comment by dmolineus** [comment]
Danke für die Bestätigung. Fix ist nun veröffentlicht als 1.0.6 des Formular-Designers
