### ISSUE TITLE
How to implement custom elements?

### ISSUE THREAD

**Issue by taleteller** [contao-bootstrap/form#34]
I am currently trying to update my taleteller/bootstrap-datepicker component to Contao4/BS4. However there is no documentation at all how to implement a custom form field into your framework. 

Can you give an example how to generate and template a simple custom field like a textbox for it renders with bootstrap classes and your form layout functionality?

**Comment by dmolineus** [comment]
I know that there is a lack of documentation. :(

However, here are some hints how it works:

1. As the base the extension [netzmacht/contao-form-designer](https://github.com/netzmacht/contao-form-designer) is used
2. It's splits the form template in different sub templates
3. To activate the form designer you have to change your `form_*` template like this one https://github.com/netzmacht/contao-form-designer/blob/master/src/Resources/contao/templates/widgets/form_textfield.html5
4. For the form element a form control template is used. For the text field it's https://github.com/netzmacht/contao-form-designer/blob/master/src/Resources/contao/templates/control/fd_control_text.html5
5. You have to add your widget to the form designer widgets configuration `netzmacht.contao_form_designer.widgets`
https://github.com/netzmacht/contao-form-designer/blob/master/src/Resources/config/config.yml#L80-L89
6. Last but not least, if you want to use some advanced bootstrap features like input group, you may have to add a contao_bootstrap.yml to your bundle and configure the widget.
https://github.com/contao-bootstrap/form/blob/master/src/Resources/config/contao_bootstrap.yml#L32-L33

Hope it gives you a glimpse how to start.
