### ISSUE TITLE
MCW issue

### ISSUE THREAD

**Issue by kikmedia** [contao-bootstrap/form#35]
After installing Form component 2.1, I've got a warning on opening the form settings:
`Warning: Illegal string offset 'widget' in /usr/local/www/data/htdocs/example.com/cms/contao/latest/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/MultiColumnWizard.php on line 499`

Using version ^3.3 for menatwork/contao-multicolumnwizard, not sure if this occurs only in forms. I'm on PHP 7.2.7.

**Comment by dmolineus** [comment]
I guess you're talking about the form layout setting? There shouldn't be the MCW in the form setting (at least not from contao-bootstrap). 

However, I can't reproduce it. Does this error still occur after saving the setting (Maybe there's a broken configuration in the database row which could not be deserialized).

**Comment by kikmedia** [comment]
You are right, it's an issue with semantic_html5 (and MCW, of course), which I was using for creating some wrappers. After uninstalling semantic_html5, the warning is gone. But I think there shouldn't be a warning in the form layout settings even if the MCW is present, or am I wrong?

**Comment by dmolineus** [comment]
As far as I see semantic_html5 should affect the form component at all. I tried to reproduce it in a current project as well, but even then installing semantic_html5 I cannot reproduce the error.

**Comment by kikmedia** [comment]
Maybe this occurs only in my very special server environment, which is different from most standard ones. So, I'm going to check this on an other server. I'm getting back to this issue afterwards.
