### ISSUE TITLE
Checkbox im Checkbox-Menü wird nicht ausgegeben.

### ISSUE THREAD

**Issue by swinde** [contao-bootstrap/form#36]
Mir ist gerade aufgefallen, das die Checkbox für obengenanntes Menü nicht angezeigt wird.
Contao 4.4.20
contao-bootstrap/form Version 2.1.1 
Link: https://test583.hostingwerk.rocks/#kontakt

Unter contao-bootstrap/form Version 2.0.0-beta-1 funktionierte das ganze noch!
Link: http://www.galabau-deubel.de/#kontakt

**Comment by dmolineus** [comment]
Ja, da hatte auch Bootstrap geändert vor der ersten stabilen Version
