### ISSUE TITLE
app.CRITICAL: An exception occurred

### ISSUE THREAD

**Issue by GMTeams** [contao-bootstrap/form#39]
PHP 7.1.10
Contao 4.4.21
contao-bootstrap/form 2.1.1

composer.json:
`"bugbuster/contao-cron-bundle": "^1.3",
        "christianbarkowsky/contao-tiny-compress-images": "^1.0",
        "codefog/contao-mobile_menu": "^2.7",
        "contao-bootstrap/form": "^2.1",
        "contao-bootstrap/grid": "^2.0",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/faq-bundle": "^4.4",
        "contao/listing-bundle": "^4.4",
        "contao/manager-bundle": "4.4.*",
        "contao/news-bundle": "^4.4",
        "contao/newsletter-bundle": "^4.4",
        "do-while/contao-backupdb-bundle": "^1.2",
        "felixpfeiffer/subcolumns": "^3.1",
        "heimrichhannot/contao-slick": "^1.6",
        "heimrichhannot/contao-subcolumns-bootstrap-bundle": "^1.2",
        "hofff/contao-googleanalytics": "^1.5",
        "hofff/contao-shariff": "^3.0",
        "jonnysp/cookieconsent": "^0.0.7",
        "phpoffice/phpexcel": "^1.8.1",
        "terminal42/contao-ajaxform": "^1.0",
        "terminal42/contao-countryselect": "^1.2",
        "terminal42/contao-leads": "^1.4",
        "terminal42/notification_center": "^1.4",
        "trilobit-gmbh/contao-formvalidation-bundle": "^1.0",
        "xraylp/contao-flickity-slider": "^2.0"`

Error log:
`app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getColumnClass\" of class \"ContaoBootstrap\\Form\\FormLayout\\DefaultFormLayout\". at /contao-project/vendor/contao-bootstrap/form/src/Resources/contao/templates/layouts/horizontal/fd_layout_bs_horizontal_double.html5:7)"} []`

Now when I try to open FE, the error occurs. When I deactivate the bootstrap form layout, the FE is fine.
Thanks for this nice extension, could you please help me with this issue.

**Comment by GMTeams** [comment]
At first, the configuration of the field "Standard Layout-Template" was "fd_layout_bs_default_double". Then I changed it to the actual configuration, but with no impact.

Screenshot:
https://bit.ly/2MIOidq

**Comment by dmolineus** [comment]
The form designer is powerful but it's also possible to break the system. The layout "fd_layout_bs_horizontal_double" is only used for the password field.

The `_horizontal` templates only work if you use a horizontal layout type. Seems like it's loaded somewhere even if you use the vertical layout.

**Comment by GMTeams** [comment]
It took me some tries, but now it works :) Thx for helping, now I understand the settings better.
