### ISSUE TITLE
Widget upload does not show an error message

### ISSUE THREAD

**Issue by zonky2** [contao-bootstrap/form#40]
Widget upload does not show an error message

![screenshot_214](https://user-images.githubusercontent.com/1045318/44897365-b4823100-acfb-11e8-97c1-ee413a062b99.jpg)

**Comment by dmolineus** [comment]
Seems to be a general issue of bootstrap, see https://github.com/twbs/bootstrap/issues/23454 or https://github.com/twbs/bootstrap/issues/27164. As a workaround I'll add d-block to the invalid-feedback message as Contao uses server side validation anyway.

Changing the template `fd_error_latest_bs` to following should solve the issue:
```php
<?php if ($this->widget->hasErrors()): ?>
    <p class="error invalid-feedback d-block"><?= $this->widget->getErrorAsString() ?></p>
<?php endif; ?>
```

**Comment by zonky2** [comment]
leider nein, behebt den Fehler nicht... offensichtlich wird das Widget gar nicht angesteuert - hier gibt es keine Ausgabe

```
<?php print_r($this->widget);die(); ?>
<?php if ($this->widget->hasErrors()): ?>
    <p class="error invalid-feedback d-block"><?= $this->widget->getErrorAsString() ?></p>
<?php endif; ?>
```

**Comment by zonky2** [comment]
nur `fd_controll_submit`

```
<?php if ($this->widget->src): ?>
    <?php
    $attributes = $this->layout->getControlAttributes($this->widget)
        ->setAttribute('type', 'image')
        ->setAttribute('src', $this->widget->src)
    ?>

    <input <?= $attributes ?>>
<?php else: ?>
    <button <?= $this->layout->getControlAttributes($this->widget) ?>><?= $this->widget->slabel ?><span class="spinner"></span></button>
<?php endif; ?>
```

**Comment by dmolineus** [comment]
Siehst du im Debug-Modus, welches ERror-Template geladen wird? Contao erzeugt dann ja HTML-Kommentare mit den Template-Namen.

**Comment by zonky2** [comment]
hatte `fd_error_latest` statt `fd_error_latest_bs` getestet - mit letzterem und `d-block` wird die Meldung angezeigt...

Notiz für Handbuch: Reihenfolge von Error und Hilfstext hier ändern https://github.com/contao-bootstrap/form/blob/master/src/Resources/contao/templates/layouts/default/fd_layout_bs_default.html5
