### ISSUE TITLE
Contao 4.6 : Registrierung

### ISSUE THREAD

**Issue by chriza** [contao-bootstrap/form#41]
Habe in eine neu aufgesetzte Contao 4.6.5 Version contao-bootrap/form eingebunden.
Das Registrierungsmodule hat ein Honeypot-Problem. Nach Deinstallation von contao-bootstrap/form nicht mehr.

**Comment by dmolineus** [comment]
Kamino closed and cloned this issue to [contao-bootstrap/templates](https://github.com/contao-bootstrap/templates/issues/18)
