### ISSUE TITLE
2.1.4 not on packagist.org

### ISSUE THREAD

**Issue by baddy1000** [contao-bootstrap/form#44]
I foolishly updated to contao 4.7. 
Now the form tool is pretty much dead.

Tried manualy requesting contao-bootstrap/form 2.1.4, to no avail.
Is there a workaround to install it regardless?

**Comment by dmolineus** [comment]
Thanks for the hint. I fixed the synchronisation. Didn't work because multiple maintainers where only one had the github hook set up.

**Comment by dmolineus** [comment]
2.1.4 should work with Contao 4.7.

**Comment by baddy1000** [comment]
Yup, works. Got it downloaded and the form issue is fixed.
Thank you <3
