### ISSUE TITLE
with a validation error I see the mesage twice

### ISSUE THREAD

**Issue by zonky2** [contao-bootstrap/form#48]
with a validation error I see the mesage twice

see

https://github.com/contao-bootstrap/form/blob/master/src/Resources/contao/templates/control/fd_control_bs_input_group.html5#L26-L28
and
https://github.com/contao-bootstrap/form/blob/master/src/Resources/contao/templates/layouts/horizontal/fd_layout_bs_horizontal.html5#L16-L18

Workaround: I disable the output/echo in fd_control_bs_input_group.html5

**Comment by dmolineus** [comment]
Fixed with 694336c9568da067114fba24a8e8cc74a9b4f2ba
