### ISSUE TITLE
Formular: Tabellen-Design mit Fieldset

### ISSUE THREAD

**Issue by mj1985** [contao-bootstrap/form#8]
Durch die Abwahl der Funktion "Tabellenloses Design" (welche so oder so tabellenlos sind), verschwindet leider auch die Option "Fieldset" aus dem Formular. 
Dies ist bei Contao anscheinend so gewollt. Möchte man nun ein 2-spaltiges Design und nimmt den Haken bei "Tabellenloses Design" raus, verschwindet auch die Option "Fieldset"

**Comment by dmolineus** [comment]
Werde im Zuge dessen auch eine bessere Beschriftung des "Tabellenloses Design" mitbringen, sodass die neue Funktion der adoptierten Einstellung verständlicher wird.
